<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Ta.Pinning 是 net8.0-windows，测试工程必须同 TFM 才能引用。 -->
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Ta.Pinning.Tests</RootNamespace>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ta.Core\Ta.Core.csproj" />
    <ProjectReference Include="..\..\src\Ta.Pinning\Ta.Pinning.csproj" />
  </ItemGroup>

</Project>
