<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Ta.AI</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ta.Core\Ta.Core.csproj" />
    <ProjectReference Include="..\Ta.Platform\Ta.Platform.csproj" />
  </ItemGroup>
</Project>