<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Ta.Windows.Core\Ta.Windows.Core.csproj" />
    <ProjectReference Include="..\Ta.Windows.Platform\Ta.Windows.Platform.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Resources\Ta.ico</ApplicationIcon>
    <SatelliteResourceLanguages>zh-Hans;en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="default-settings.json" LogicalName="Ta.Windows.App.default-settings.json" />
  </ItemGroup>

</Project>
